In [1]:
# basic import statements
import os
import re
import gc
import warnings
import numpy as np
import pandas as pd
import collections
warnings.filterwarnings("ignore")
from datetime import date 

#set max display in notebook
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

#Show multiple output in console
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

### Honda Data

In [2]:
df1 = pd.read_csv('honda_sell_data.csv')
df1.shape
df1.head()

(4999, 25)

   Year   Make                      Model Condition    Price  Consumer_Rating  Consumer_Review_#           Exterior_Color Interior_Color         Drivetrain    MPG Fuel_Type       Transmission                       Engine                VIN   Stock_# Mileage  Comfort_Rating  Interior_Design_Rating  Performance_Rating  Value_For_Money_Rating  Exterior_Styling_Rating  Reliability_Rating State Seller_Type
0  2023  Honda              Ridgeline RTL       New  $46,370              4.8                  9     Platinum White Pearl          Beige    All-wheel Drive    NaN  Gasoline          Automatic         3.5L V6 24V GDI SOHC  5FPYK3F58PB011817  00830164      10             5.0                     4.8                 4.8                     4.2                      5.0                 5.0    CA      Dealer
1  2023  Honda          CR-V Hybrid Sport       New  $34,150              1.7                 24     Platinum White Pearl          Black                FWD    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid  2HKRS5H5XPH702953   6402953       –             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA      Dealer
2  2023  Honda          CR-V Hybrid Sport       New  $34,245              4.7               2869  Meteorite Gray Metallic          Black  Front-wheel Drive    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid  2HKRS5H55PH704805  PH704805       1             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA      Dealer
3  2022  Honda           Pilot TrailSport       New  $46,500              5.0                 12         Sonic Gray Pearl          Black    All-wheel Drive  19–25  Gasoline  9-Speed Automatic         3.5L V6 24V GDI SOHC  5FNYF6H82NB100429  5700429B       5             5.0                     5.0                 5.0                     5.0                      5.0                 5.0    CA      Dealer
4  2023  Honda  CR-V Hybrid Sport Touring       New  $40,395              4.4                 12      Crystal Black Pearl          Black    All-wheel Drive    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid  2HKRS6H90PH805954   5705954       5             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA      Dealer

In [3]:
df1.Condition.value_counts()

New                2697
Used               2022
Honda Certified     280
Name: Condition, dtype: int64

In [4]:
df1.Model.value_counts()

CR-V EX-L                                             268
Pilot Sport                                           228
Pilot EX-L                                            204
Accord Sport 1.5T                                     195
CR-V Hybrid Sport Touring                             185
CR-V EX                                               178
Odyssey EX-L                                          174
Civic Sport                                           160
Pilot TrailSport                                      150
Ridgeline RTL-E                                       144
Pilot Special Edition                                 136
Passport EX-L                                         128
Ridgeline RTL                                         119
Odyssey Elite                                         109
Accord Hybrid Sport                                   100
Civic Si Base                                          98
Passport Elite                                         97
Civic EX                                               95
Civic LX                                               93
Pilot Elite                                            89
Odyssey Touring                                        88
Passport TrailSport                                    87
HR-V Sport                                             84
Pilot Touring                                          74
Accord Sport 2.0T                                      69
Ridgeline Black Edition                                68
Passport Sport                                         64
CR-V Hybrid Sport                                      55
Pilot Touring 7-Passenger                              54
HR-V LX                                                54
CR-V Touring                                           49
Passport Touring                                       49
HR-V EX-L                                              48
Accord LX                                              47
Odyssey Sport                                          46
Insight EX                                             40
Civic Sport Touring                                    40
Pilot EX-L 8-Passenger                                 39
Insight Touring                                        39
Accord Sport                                           39
HR-V EX                                                37
Accord Sport SE                                        37
Accord EX-L                                            36
Ridgeline Sport                                        34
Accord Hybrid Touring                                  34
Pilot EX                                               34
CR-V LX                                                34
Civic Type R Touring                                   33
Accord EX                                              33
Pilot Touring 8-Passenger                              31
Pilot Black Edition                                    27
Civic Touring                                          26
Odyssey EX                                             25
Civic EX-L                                             25
CR-V Hybrid Touring                                    24
Accord LX 1.5T                                         22
Pilot EX-L 7-Passenger                                 22
Civic Si                                               17
Accord Hybrid EX-L                                     16
Clarity Plug-In Hybrid Touring                         16
Clarity Plug-In Hybrid Base                            14
Accord Hybrid Base                                     14
CR-V Hybrid EX-L                                       13
Pilot LX                                               12
Accord Touring                                         12
Odyssey LX                                             11
Crosstour EX-L                                         11
Accord Touring 2.0T                                    11
Ridgeline RTL-T                                        10
Fit LX                                                 10
Odyssey SE                                             10
CR-Z EX                                                 9
Civic EX-T                                              9
Element EX                                              8
S2000                                                   8
CR-V Special Edition                                    7
Element LX                                              7
Accord EX 1.5T                                          7
CR-V Hybrid EX                                          6
Odyssey EX-L w/Navigation/RES                           6
HR-V EX-L w/Navigation                                  6
Accord Crosstour EX-L                                   6
Pilot EX-L w/ Navigation                                6
Civic Hybrid                                            5
Civic Type R Limited Edition                            5
Fit Sport                                               5
Insight LX                                              5
Prelude                                                 5
Fit EX                                                  5
Ridgeline SE                                            4
Fit EX-L                                                4
Odyssey Touring Elite                                   4
Crosstour EX                                            4
S2000 Base (M6)                                         4
Accord SE                                               4
Element EX-P                                            4
CR-V SE                                                 4
Civic Si Manual                                         3
Ridgeline RT                                            3
Accord EX-L 1.5T                                        3
Accord Hybrid EX                                        3
Accord EX-L 2.0T                                        3
Accord Sport SE 1.5T                                    3
Civic Si Si                                             3
CR-Z Base                                               3
Fit                                                     3
Ridgeline Black                                         3
del Sol Si                                              2
Prelude Si                                              2
Odyssey                                                 2
Civic LX-P                                              2
HR-V Touring                                            2
Accord LX-S                                             2
Accord LX-P                                             2
S2000 Base                                              2
Pilot SE                                                2
Pilot EX-L w/Navigation/RES                             1
Civic Si Sedan                                          1
Civic EX-L w/Navi                                       1
Fit Base                                                1
Civic Si SI                                             1
CR-Z 3dr CVT                                            1
Civic Si Base w/Summer Tires (M6)                       1
Civic GX                                                1
Insight                                                 1
Civic Hybrid Base w/Leather (CVT)                       1
Pilot VP                                                1
Ridgeline RTS                                           1
Fit Sport w/ Navigation                                 1
Accord Crosstour                                        1
Civic Si Base (M6)                                      1
Prelude Type SH                                         1
Fit Base (A5)                                           1
Accord Hybrid Sport-L                                   1
Accord Plug-In Hybrid Base                              1
Civic Hybrid Base                                       1
Civic Si Base w/High Performance Summer Tires (M6)      1
Civic LX-S                                              1
Prelude Si 4WS                                          1
CR-Z LX                                                 1
CR-Z EX-L                                               1
Ridgeline RTX                                           1
Odyssey EX-L/RES                                        1
Accord VP                                               1
CR-Z Base (M6)                                          1
Accord EX-L V-6                                         1
Name: Model, dtype: int64

In [5]:
df1 = df1[df1.Condition=='New']
df1.shape
df1.head()

(2697, 25)

   Year   Make                      Model Condition    Price  Consumer_Rating  Consumer_Review_#           Exterior_Color Interior_Color         Drivetrain    MPG Fuel_Type       Transmission                       Engine                VIN   Stock_# Mileage  Comfort_Rating  Interior_Design_Rating  Performance_Rating  Value_For_Money_Rating  Exterior_Styling_Rating  Reliability_Rating State Seller_Type
0  2023  Honda              Ridgeline RTL       New  $46,370              4.8                  9     Platinum White Pearl          Beige    All-wheel Drive    NaN  Gasoline          Automatic         3.5L V6 24V GDI SOHC  5FPYK3F58PB011817  00830164      10             5.0                     4.8                 4.8                     4.2                      5.0                 5.0    CA      Dealer
1  2023  Honda          CR-V Hybrid Sport       New  $34,150              1.7                 24     Platinum White Pearl          Black                FWD    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid  2HKRS5H5XPH702953   6402953       –             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA      Dealer
2  2023  Honda          CR-V Hybrid Sport       New  $34,245              4.7               2869  Meteorite Gray Metallic          Black  Front-wheel Drive    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid  2HKRS5H55PH704805  PH704805       1             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA      Dealer
3  2022  Honda           Pilot TrailSport       New  $46,500              5.0                 12         Sonic Gray Pearl          Black    All-wheel Drive  19–25  Gasoline  9-Speed Automatic         3.5L V6 24V GDI SOHC  5FNYF6H82NB100429  5700429B       5             5.0                     5.0                 5.0                     5.0                      5.0                 5.0    CA      Dealer
4  2023  Honda  CR-V Hybrid Sport Touring       New  $40,395              4.4                 12      Crystal Black Pearl          Black    All-wheel Drive    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid  2HKRS6H90PH805954   5705954       5             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA      Dealer

In [7]:
df1.Seller_Type.value_counts()

Dealer    2690
Name: Seller_Type, dtype: int64

In [10]:
df1 = df1.drop(columns=['Condition','Consumer_Review_#','VIN','Stock_#','Seller_Type'])
df1.shape
df1.head()

(2697, 20)

   Year   Make                      Model    Price  Consumer_Rating           Exterior_Color Interior_Color         Drivetrain    MPG Fuel_Type       Transmission                       Engine Mileage  Comfort_Rating  Interior_Design_Rating  Performance_Rating  Value_For_Money_Rating  Exterior_Styling_Rating  Reliability_Rating State
0  2023  Honda              Ridgeline RTL  $46,370              4.8     Platinum White Pearl          Beige    All-wheel Drive    NaN  Gasoline          Automatic         3.5L V6 24V GDI SOHC      10             5.0                     4.8                 4.8                     4.2                      5.0                 5.0    CA
1  2023  Honda          CR-V Hybrid Sport  $34,150              1.7     Platinum White Pearl          Black                FWD    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid       –             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA
2  2023  Honda          CR-V Hybrid Sport  $34,245              4.7  Meteorite Gray Metallic          Black  Front-wheel Drive    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid       1             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA
3  2022  Honda           Pilot TrailSport  $46,500              5.0         Sonic Gray Pearl          Black    All-wheel Drive  19–25  Gasoline  9-Speed Automatic         3.5L V6 24V GDI SOHC       5             5.0                     5.0                 5.0                     5.0                      5.0                 5.0    CA
4  2023  Honda  CR-V Hybrid Sport Touring  $40,395              4.4      Crystal Black Pearl          Black    All-wheel Drive    NaN    Hybrid      Automatic CVT  2.0L I4 16V GDI DOHC Hybrid       5             5.0                     3.0                 4.0                     4.0                      5.0                 5.0    CA

In [58]:
df1.to_excel('honda_data.xlsx',index=False)

In [62]:
for col in df1.columns:
    print(col)

Year
Make
Model
Price
Consumer_Rating
Exterior_Color
Interior_Color
Drivetrain
MPG
Fuel_Type
Transmission
Engine
Mileage
Comfort_Rating
Interior_Design_Rating
Performance_Rating
Value_For_Money_Rating
Exterior_Styling_Rating
Reliability_Rating
State

In [65]:
df1.Model.value_counts()

Pilot Sport                     217
CR-V EX-L                       189
CR-V Hybrid Sport Touring       185
Accord Sport 1.5T               158
Pilot TrailSport                145
CR-V EX                         107
Ridgeline RTL-E                 106
Pilot Special Edition           104
Accord Hybrid Sport              86
Ridgeline RTL                    85
Pilot EX-L                       83
Civic Sport                      82
HR-V Sport                       74
Passport TrailSport              69
Odyssey Elite                    62
Pilot Elite                      59
Pilot Touring                    54
Accord Sport 2.0T                54
CR-V Hybrid Sport                54
Odyssey Touring                  53
Passport Elite                   53
Ridgeline Black Edition          52
Passport EX-L                    50
Odyssey EX-L                     50
Civic Si Base                    45
Odyssey Sport                    42
HR-V EX-L                        39
Pilot EX-L 8-Passenger           39
Pilot Touring 7-Passenger        32
Civic Sport Touring              31
Accord Sport SE                  28
Civic EX                         27
HR-V LX                          27
Pilot EX-L 7-Passenger           22
Civic Touring                    16
Pilot Black Edition              14
Civic EX-L                       13
CR-V Touring                     12
Pilot Touring 8-Passenger        10
Accord EX                         9
HR-V EX                           7
Accord Sport                      7
Accord Hybrid Touring             6
Civic Si                          5
CR-V Hybrid Touring               5
Civic Type R Touring              4
Accord Hybrid Base                4
Accord LX                         3
Civic Si Manual                   3
Accord LX 1.5T                    2
Ridgeline Black                   2
Civic Type R Limited Edition      1
Civic Si Sedan                    1
Civic Si Si                       1
CR-V Special Edition              1
Accord Hybrid Sport-L             1
Accord Touring 2.0T               1
Civic Si SI                       1
Accord Sport SE 1.5T              1
Accord Touring                    1
CR-V LX                           1
Accord EX-L 1.5T                  1
CR-V Hybrid EX-L                  1
Name: Model, dtype: int64

### Honda Car Sales Data

In [20]:
df2 = pd.read_csv('car_sales_data.csv')
df2.shape
df2.head()

(2500000, 9)

         Date      Salesperson   Customer Name Car Make  Car Model  Car Year  Sale Price  Commission Rate  Commission Earned
0  2022-08-01  Monica Moore MD     Mary Butler   Nissan     Altima      2018       15983         0.070495            1126.73
1  2023-03-15     Roberto Rose  Richard Pierce   Nissan      F-150      2016       38474         0.134439            5172.40
2  2023-04-29     Ashley Ramos    Sandra Moore     Ford      Civic      2016       33340         0.114536            3818.63
3  2022-09-04   Patrick Harris    Johnny Scott     Ford     Altima      2013       41937         0.092191            3866.20
4  2022-06-16       Eric Lopez   Vanessa Jones    Honda  Silverado      2022       20256         0.113490            2298.85

In [21]:
for col in df2.columns:
    print(col)

Date
Salesperson
Customer Name
Car Make
Car Model
Car Year
Sale Price
Commission Rate
Commission Earned

In [22]:
df2 = df2.rename(columns={"Customer Name": "Customer_Name", "Car Make": "Car_Make","Car Model":"Car_Model","Car Year":"Car_year","Sale Price":"Sale_Price","Commission Rate":"Commission_Rate","Commission Earned":"Commission_Earned"})
df2.shape
df2.head()

(2500000, 9)

         Date      Salesperson   Customer_Name Car_Make  Car_Model  Car_year  Sale_Price  Commission_Rate  Commission_Earned
0  2022-08-01  Monica Moore MD     Mary Butler   Nissan     Altima      2018       15983         0.070495            1126.73
1  2023-03-15     Roberto Rose  Richard Pierce   Nissan      F-150      2016       38474         0.134439            5172.40
2  2023-04-29     Ashley Ramos    Sandra Moore     Ford      Civic      2016       33340         0.114536            3818.63
3  2022-09-04   Patrick Harris    Johnny Scott     Ford     Altima      2013       41937         0.092191            3866.20
4  2022-06-16       Eric Lopez   Vanessa Jones    Honda  Silverado      2022       20256         0.113490            2298.85

In [24]:
df2 = df2[df2.Car_Make == 'Honda']
df2.shape
df2.head()

(500687, 9)

          Date      Salesperson     Customer_Name Car_Make  Car_Model  Car_year  Sale_Price  Commission_Rate  Commission_Earned
4   2022-06-16       Eric Lopez     Vanessa Jones    Honda  Silverado      2022       20256         0.113490            2298.85
6   2022-06-12     Ashley Brown      Tyler Lawson    Honda      F-150      2013       41397         0.142780            5910.67
10  2023-03-12    Harold Nelson      Isaac Patton    Honda  Silverado      2021       41259         0.092541            3818.16
15  2022-12-21  James Velasquez  Natalie Thompson    Honda    Corolla      2016       36607         0.055251            2022.57
25  2023-02-15     Faith Pierce        Jimmy Dunn    Honda  Silverado      2016       35279         0.063400            2236.68

In [59]:
df2.to_excel('honda_sales_data.xlsx',index=False)

### Sentiment analysis from Car Reviews

In [27]:
df3 = pd.read_excel('Scrapped_Car_Reviews_Honda.xlsx')
df3.shape
df3.head()

(14213, 7)

  Unnamed: 0                  Review_Date      Author_Name                                      Vehicle_Title                        Review_Title                                             Review  Rating
0          0   on 03/01/17 13:11 PM (PST)      kris corah   2007 Honda Element SUV LX 4dr SUV AWD (2.4L 4c...                QUIRKY AND PRACTICAL   4 years with our element. Honestly there isn'...     4.0
1          1   on 09/02/16 18:22 PM (PDT)  Carol Shafford   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...       Go Anywhere with your Element   I have owned my Element since 2007 when I pur...     5.0
2          2   on 11/12/15 08:04 AM (PST)            Gale   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...                    Such a cool car!   Lowest maintenance of any vehicle I've ever o...     1.0
3          3   on 08/13/15 15:40 PM (PDT)    Judy Eastham    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5M)  From soup to nuts, it does it all.   The only thing I'd change is the drink holder...     5.0
4          4   on 03/14/13 10:38 AM (PDT)  boeserkritiker    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5A)                          good value   I bought this vehicle new in 2007. got 97K mi...     4.0

In [28]:
import nltk
import re
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kothaapuroop/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [30]:
# Remove unwanted columns
df3 = df3.drop(columns=['Unnamed: 0'])

In [32]:
df3[df3.isna().any(axis=1)]

                       Review_Date  Author_Name                                      Vehicle_Title                          Review_Title                                             Review  Rating
585     on 09/04/14 09:21 AM (PDT)      rsxing   2014 Honda Accord Hybrid Sedan Touring 4dr Sed...    2014 Accord Hybrid Touring MPG WTF   I purchased 2 Honda Accord Hybrid Touring sed...     NaN
586                           4.25          NaN                                                NaN                                   NaN                                                NaN     NaN
621     on 03/04/04 00:00 AM (PST)  Tim Guiles   2003 Honda Insight Hatchback 2dr Hatchback (1....  It doesn't get any better than this!        In the summer I get 85 miles to the gallon      NaN
622                            NaN          NaN                                                NaN                                   NaN                                                NaN     NaN
623                            NaN          NaN                                                NaN                                   NaN                                                NaN     NaN
...                            ...          ...                                                ...                                   ...                                                ...     ...
12843                          NaN          NaN                                                NaN                                   NaN                                                NaN     NaN
12844                        3.625          NaN                                                NaN                                   NaN                                                NaN     NaN
13028   on 02/24/16 12:14 PM (PST)         Lee      2011 Honda Pilot SUV LX 4dr SUV (3.5L 6cyl 5A)                                   NaN                                                        4.0
13459   on 09/02/14 23:32 PM (PDT)   dabizmike   2014 Honda Pilot SUV EX 4dr SUV 4WD (3.5L 6cyl...                             Not a 4WD   Bought this after salesman said this was 4WD ...     NaN
13460                            2          NaN                                                NaN                                   NaN                                                NaN     NaN

[1831 rows x 6 columns]

In [34]:
# Handle missing data
df3.dropna(inplace=True)

In [35]:
# Text preprocessing
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # Remove non-alphabetic characters
    words = text.split()
    words = [word for word in words if word not in stopwords.words('english')]  # Remove stopwords
    return ' '.join(words)

In [36]:
df3['Review'] = df3['Review'].apply(preprocess_text)
df3.shape
df3.head()

(12382, 6)

                   Review_Date      Author_Name                                      Vehicle_Title                        Review_Title                                             Review  Rating
0   on 03/01/17 13:11 PM (PST)      kris corah   2007 Honda Element SUV LX 4dr SUV AWD (2.4L 4c...                QUIRKY AND PRACTICAL  years element honestly much complain never gre...     4.0
1   on 09/02/16 18:22 PM (PDT)  Carol Shafford   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...       Go Anywhere with your Element  owned element since purchased new great little...     5.0
2   on 11/12/15 08:04 AM (PST)            Gale   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...                    Such a cool car!  lowest maintenance vehicle ever owned time mov...     1.0
3   on 08/13/15 15:40 PM (PDT)    Judy Eastham    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5M)  From soup to nuts, it does it all.  thing change drink holders hard get arm love c...     5.0
4   on 03/14/13 10:38 AM (PDT)  boeserkritiker    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5A)                          good value  bought vehicle new got k miles served us relia...     4.0

In [37]:
#Analysis

from textblob import TextBlob

# Perform sentiment analysis and store the results in a new column
df3['Sentiment'] = df3['Review'].apply(lambda x: TextBlob(x).sentiment.polarity)
df3.shape
df3.head()

(12382, 7)

                   Review_Date      Author_Name                                      Vehicle_Title                        Review_Title                                             Review  Rating  Sentiment
0   on 03/01/17 13:11 PM (PST)      kris corah   2007 Honda Element SUV LX 4dr SUV AWD (2.4L 4c...                QUIRKY AND PRACTICAL  years element honestly much complain never gre...     4.0   0.142614
1   on 09/02/16 18:22 PM (PDT)  Carol Shafford   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...       Go Anywhere with your Element  owned element since purchased new great little...     5.0   0.318987
2   on 11/12/15 08:04 AM (PST)            Gale   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...                    Such a cool car!  lowest maintenance vehicle ever owned time mov...     1.0   0.361905
3   on 08/13/15 15:40 PM (PDT)    Judy Eastham    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5M)  From soup to nuts, it does it all.  thing change drink holders hard get arm love c...     5.0   0.169356
4   on 03/14/13 10:38 AM (PDT)  boeserkritiker    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5A)                          good value  bought vehicle new got k miles served us relia...     4.0  -0.019043

In [39]:
average_sentiment = df3['Sentiment'].mean()
print(f'Average Sentiment Score: {average_sentiment}')

Average Sentiment Score: 0.208097428514468

#### Positive and Negative Reviews

In [40]:
# Define a threshold for positive and negative sentiment
threshold = 0.0

# Create a new column to categorize reviews
df3['Sentiment_Category'] = df3['Sentiment'].apply(lambda x: 'Positive' if x > threshold else 'Negative' if x < -threshold else 'Neutral')

In [41]:
df3.shape
df3.head()

(12382, 8)

                   Review_Date      Author_Name                                      Vehicle_Title                        Review_Title                                             Review  Rating  Sentiment Sentiment_Category
0   on 03/01/17 13:11 PM (PST)      kris corah   2007 Honda Element SUV LX 4dr SUV AWD (2.4L 4c...                QUIRKY AND PRACTICAL  years element honestly much complain never gre...     4.0   0.142614           Positive
1   on 09/02/16 18:22 PM (PDT)  Carol Shafford   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...       Go Anywhere with your Element  owned element since purchased new great little...     5.0   0.318987           Positive
2   on 11/12/15 08:04 AM (PST)            Gale   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...                    Such a cool car!  lowest maintenance vehicle ever owned time mov...     1.0   0.361905           Positive
3   on 08/13/15 15:40 PM (PDT)    Judy Eastham    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5M)  From soup to nuts, it does it all.  thing change drink holders hard get arm love c...     5.0   0.169356           Positive
4   on 03/14/13 10:38 AM (PDT)  boeserkritiker    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5A)                          good value  bought vehicle new got k miles served us relia...     4.0  -0.019043           Negative

#### Tokenize and count words

In [43]:
from collections import Counter
from nltk.tokenize import word_tokenize

# Tokenize the reviews
df3['Tokenized_Review'] = df3['Review'].apply(word_tokenize)

In [44]:
df3.shape

(12382, 9)

In [45]:
df3.head()

                   Review_Date      Author_Name                                      Vehicle_Title                        Review_Title                                             Review  Rating  Sentiment Sentiment_Category                                   Tokenized_Review
0   on 03/01/17 13:11 PM (PST)      kris corah   2007 Honda Element SUV LX 4dr SUV AWD (2.4L 4c...                QUIRKY AND PRACTICAL  years element honestly much complain never gre...     4.0   0.142614           Positive  [years, element, honestly, much, complain, nev...
1   on 09/02/16 18:22 PM (PDT)  Carol Shafford   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...       Go Anywhere with your Element  owned element since purchased new great little...     5.0   0.318987           Positive  [owned, element, since, purchased, new, great,...
2   on 11/12/15 08:04 AM (PST)            Gale   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...                    Such a cool car!  lowest maintenance vehicle ever owned time mov...     1.0   0.361905           Positive  [lowest, maintenance, vehicle, ever, owned, ti...
3   on 08/13/15 15:40 PM (PDT)    Judy Eastham    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5M)  From soup to nuts, it does it all.  thing change drink holders hard get arm love c...     5.0   0.169356           Positive  [thing, change, drink, holders, hard, get, arm...
4   on 03/14/13 10:38 AM (PDT)  boeserkritiker    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5A)                          good value  bought vehicle new got k miles served us relia...     4.0  -0.019043           Negative  [bought, vehicle, new, got, k, miles, served, ...

In [47]:
# Separate positive and negative reviews
positive_reviews = df3[df3['Sentiment_Category'] == 'Positive']
negative_reviews = df3[df3['Sentiment_Category'] == 'Negative']

# Count words in positive and negative reviews
positive_word_counts = Counter()
negative_word_counts = Counter()

for review in positive_reviews['Tokenized_Review']:
    positive_word_counts.update(review)

for review in negative_reviews['Tokenized_Review']:
    negative_word_counts.update(review)

In [48]:
# Get the most frequent words in positive reviews
most_common_positive_words = positive_word_counts.most_common(10)

# Get the most frequent words in negative reviews
most_common_negative_words = negative_word_counts.most_common(10)

print("Most Common Words in Positive Reviews:")
for word, count in most_common_positive_words:
    print(f"{word}: {count}")

print("\nMost Common Words in Negative Reviews:")
for word, count in most_common_negative_words:
    print(f"{word}: {count}")

Most Common Words in Positive Reviews:
car: 16187
x: 9792
honda: 7539
great: 5474
miles: 5309
like: 3788
drive: 3759
mpg: 3562
good: 3423
get: 3420

Most Common Words in Negative Reviews:
car: 2146
honda: 1846
x: 1198
miles: 851
k: 489
get: 480
bought: 478
transmission: 466
like: 452
new: 441

#### Understanding the context of the reviews

In [49]:
from nltk.util import ngrams

# Define a function to extract n-grams from a list of tokens
def get_ngrams(tokens, n):
    return list(ngrams(tokens, n))

In [50]:
# Tokenize the reviews
df3['Tokenized_Review'] = df3['Review'].apply(word_tokenize)
df3.shape
df3.head()

(12382, 9)

                   Review_Date      Author_Name                                      Vehicle_Title                        Review_Title                                             Review  Rating  Sentiment Sentiment_Category                                   Tokenized_Review
0   on 03/01/17 13:11 PM (PST)      kris corah   2007 Honda Element SUV LX 4dr SUV AWD (2.4L 4c...                QUIRKY AND PRACTICAL  years element honestly much complain never gre...     4.0   0.142614           Positive  [years, element, honestly, much, complain, nev...
1   on 09/02/16 18:22 PM (PDT)  Carol Shafford   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...       Go Anywhere with your Element  owned element since purchased new great little...     5.0   0.318987           Positive  [owned, element, since, purchased, new, great,...
2   on 11/12/15 08:04 AM (PST)            Gale   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...                    Such a cool car!  lowest maintenance vehicle ever owned time mov...     1.0   0.361905           Positive  [lowest, maintenance, vehicle, ever, owned, ti...
3   on 08/13/15 15:40 PM (PDT)    Judy Eastham    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5M)  From soup to nuts, it does it all.  thing change drink holders hard get arm love c...     5.0   0.169356           Positive  [thing, change, drink, holders, hard, get, arm...
4   on 03/14/13 10:38 AM (PDT)  boeserkritiker    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5A)                          good value  bought vehicle new got k miles served us relia...     4.0  -0.019043           Negative  [bought, vehicle, new, got, k, miles, served, ...

In [53]:
# Extract and count bi-grams or trigrams in positive and negative reviews
positive_reviews['Bi-grams'] = positive_reviews['Tokenized_Review'].apply(lambda x: get_ngrams(x, 3))  # Change 2 to 3 for trigrams
negative_reviews['Bi-grams'] = negative_reviews['Tokenized_Review'].apply(lambda x: get_ngrams(x, 3))  # Change 2 to 3 for trigrams

In [54]:
# Count the frequency of bi-grams or trigrams
positive_bi_gram_counts = Counter()
negative_bi_gram_counts = Counter()

for bi_grams in positive_reviews['Bi-grams']:
    positive_bi_gram_counts.update(bi_grams)

for bi_grams in negative_reviews['Bi-grams']:
    negative_bi_gram_counts.update(bi_grams)

In [55]:
positive_bi_gram_counts

Counter({('years', 'element'): 1,
         ('element', 'honestly'): 2,
         ('honestly', 'much'): 1,
         ('much', 'complain'): 2,
         ('complain', 'never'): 1,
         ('never', 'grew'): 2,
         ('grew', 'love'): 1,
         ('love', 'transmission'): 2,
         ('transmission', 'annoys'): 1,
         ('annoys', 'constantly'): 1,
         ('constantly', 'hunting'): 3,
         ('hunting', 'thru'): 1,
         ('thru', 'gear'): 1,
         ('gear', 'yes'): 1,
         ('yes', 'know'): 2,
         ('know', 'getting'): 8,
         ('getting', 'best'): 7,
         ('best', 'mileage'): 21,
         ('mileage', 'shifts'): 1,
         ('shifts', 'hard'): 3,
         ('hard', 'harsh'): 1,
         ('harsh', 'fact'): 1,
         ('fact', 'unpleasant'): 1,
         ('unpleasant', 'find'): 1,
         ('find', 'annoying'): 4,
         ('annoying', 'listening'): 1,
         ('listening', 'engine'): 1,
         ('engine', 'cycle'): 1,
         ('cycle', 'trans'): 1,
         ('trans', 'constantly'): 1,
         ('constantly', 'shifts'): 1,
         ('shifts', 'every'): 1,
         ('every', 'rise'): 1,
         ('rise', 'dip'): 1,
         ('dip', 'road'): 2,
         ('road', 'highway'): 7,
         ('highway', 'truly'): 1,
         ('truly', 'busy'): 1,
         ('busy', 'transmission'): 1,
         ('transmission', 'road'): 1,
         ('road', 'noise'): 499,
         ('noise', 'bit'): 6,
         ('bit', 'loud'): 7,
         ('loud', 'side'): 1,
         ('side', 'well'): 2,
         ('well', 'crosswinds'): 1,
         ('crosswinds', 'fairly'): 1,
         ('fairly', 'disruptive'): 1,
         ('disruptive', 'pushing'): 1,
         ('pushing', 'car'): 2,
         ('car', 'around'): 33,
         ('around', 'road'): 3,
         ('road', 'rear'): 2,
         ('rear', 'doors'): 19,
         ('doors', 'love'): 4,
         ('love', 'hate'): 9,
         ('hate', 'item'): 1,
         ('item', 'well'): 1,
         ('well', 'different'): 1,
         ('different', 'routine'): 1,
         ('routine', 'using'): 1,
         ('using', 'parking'): 1,
         ('parking', 'lots'): 24,
         ('lots', 'requires'): 1,
         ('requires', 'forethought'): 1,
         ('forethought', 'getting'): 1,
         ('getting', 'kids'): 3,
         ('kids', 'exercise'): 1,
         ('exercise', 'frustration'): 1,
         ('frustration', 'trapped'): 1,
         ('trapped', 'doors'): 1,
         ('doors', 'many'): 1,
         ('many', 'times'): 50,
         ('times', 'sort'): 1,
         ('sort', 'dance'): 1,
         ('dance', 'juggling'): 1,
         ('juggling', 'get'): 1,
         ('get', 'position'): 1,
         ('position', 'able'): 1,
         ('able', 'get'): 56,
         ('get', 'doors'): 2,
         ('doors', 'closed'): 1,
         ('closed', 'doors'): 1,
         ('doors', 'open'): 25,
         ('open', 'degrees'): 2,
         ('degrees', 'makes'): 2,
         ('makes', 'getting'): 3,
         ('getting', 'loading'): 1,
         ('loading', 'easier'): 1,
         ('easier', 'brings'): 1,
         ('brings', 'doors'): 1,
         ('doors', 'range'): 1,
         ('range', 'neighboring'): 1,
         ('neighboring', 'cars'): 1,
         ('cars', 'parking'): 1,
         ('lots', 'yr'): 1,
         ('yr', 'old'): 32,
         ('old', 'leans'): 1,
         ('leans', 'door'): 1,
         ('door', 'get'): 4,
         ('get', 'simple'): 3,
         ('simple', 'door'): 1,
         ('door', 'swing'): 1,
         ('swing', 'open'): 2,
         ('open', 'enough'): 2,
         ('enough', 'bump'): 1,
         ('bump', 'car'): 1,
         ('car', 'beside'): 2,
         ('beside', 'aside'): 1,
         ('aside', 'low'): 1,
         ('low', 'tire'): 6,
         ('tire', 'pressure'): 43,
         ('pressure', 'monitor'): 3,
         ('monitor', 'coming'): 1,
         ('coming', 'staying'): 1,
         ('staying', 'year'): 1,
         ('year', 'got'): 8,
         ('got', 'car'): 111,
         ('car', 'almost'): 55,
         ('almost', 'faultless'): 1,
         ('faultless', 'fuel'): 1,
         ('fuel', 'mileage'): 83,
         ('mileage', 'good'): 83,
         ('good', 'get'): 11,
         ('get', 'time'): 3,
         ('time', 'mile'): 3,
         ('mile', 'less'): 1,
         ('less', 'winter'): 2,
         ('winter', 'get'): 4,
         ('get', 'highway'): 23,
         ('highway', 'speed'): 25,
         ('speed', 'best'): 5,
         ('mileage', 'seen'): 1,
         ('seen', 'plus'): 1,
         ('plus', 'side'): 7,
         ('side', 'roomy'): 1,
         ('roomy', 'size'): 5,
         ('size', 'seats'): 4,
         ('seats', 'fold'): 46,
         ('fold', 'flat'): 16,
         ('flat', 'swing'): 1,
         ('swing', 'clearing'): 1,
         ('clearing', 'floor'): 1,
         ('floor', 'removed'): 1,
         ('removed', 'rather'): 1,
         ('rather', 'take'): 1,
         ('take', 'punch'): 1,
         ('punch', 'mike'): 1,
         ('mike', 'tyson'): 1,
         ('tyson', 'year'): 1,
         ('year', 'old'): 156,
         ('old', 'loves'): 3,
         ('loves', 'decorate'): 1,
         ('decorate', 'car'): 1,
         ('car', 'drawing'): 1,
         ('drawing', 'matte'): 1,
         ('matte', 'black'): 1,
         ('black', 'plastic'): 4,
         ('plastic', 'panels'): 3,
         ('panels', 'sidewalk'): 1,
         ('sidewalk', 'chalk'): 1,
         ('chalk', 'nice'): 1,
         ('nice', 'conversation'): 1,
         ('conversation', 'piece'): 3,
         ('piece', 'people'): 2,
         ('people', 'wife'): 1,
         ('wife', 'work'): 1,
         ('work', 'love'): 4,
         ('love', 'excellent'): 3,
         ('excellent', 'choice'): 11,
         ('choice', 'someone'): 1,
         ('someone', 'small'): 1,
         ('small', 'kids'): 3,
         ('kids', 'dogs'): 7,
         ('dogs', 'fold'): 1,
         ('fold', 'back'): 13,
         ('back', 'flat'): 2,
         ('flat', 'one'): 2,
         ('one', 'seat'): 2,
         ('seat', 'rear'): 5,
         ('rear', 'great'): 2,
         ('great', 'dane'): 6,
         ('dane', 'lays'): 1,
         ('lays', 'next'): 1,
         ('next', 'kid'): 1,
         ('kid', 'car'): 4,
         ('car', 'seat'): 47,
         ('seat', 'still'): 9,
         ('still', 'thing'): 2,
         ('thing', 'probably'): 2,
         ('probably', 'trading'): 1,
         ('trading', 'next'): 1,
         ('next', 'months'): 1,
         ('months', 'decide'): 1,
         ('decide', 'replacement'): 1,
         ('replacement', 'held'): 1,
         ('held', 'pretty'): 4,
         ('pretty', 'well'): 34,
         ('well', 'seats'): 6,
         ('seats', 'stains'): 1,
         ('stains', 'passenger'): 1,
         ('passenger', 'side'): 106,
         ('side', 'dash'): 5,
         ('dash', 'weird'): 1,
         ('weird', 'discoloration'): 1,
         ('discoloration', 'accent'): 1,
         ('accent', 'panel'): 1,
         ('panel', 'tach'): 2,
         ('tach', 'needle'): 1,
         ('needle', 'fell'): 1,
         ('fell', 'months'): 1,
         ('months', 'ago'): 96,
         ('ago', 'rust'): 1,
         ('rust', 'spot'): 2,
         ('spot', 'driverside'): 1,
         ('driverside', 'rear'): 2,
         ('rear', 'door'): 27,
         ('door', 'al'): 1,
         ('al', 'got'): 1,
         ('got', 'moneys'): 1,
         ('moneys', 'worth'): 3,
         ('worth', 'going'): 3,
         ('going', 'miles'): 8,
         ('owned', 'element'): 4,
         ('element', 'since'): 1,
         ('since', 'purchased'): 31,
         ('purchased', 'new'): 103,
         ('new', 'great'): 15,
         ('great', 'little'): 76,
         ('little', 'suv'): 29,
         ('suv', 'almost'): 3,
         ('almost', 'miles'): 49,
         ('miles', 'plow'): 1,
         ('plow', 'snow'): 1,
         ('snow', 'best'): 2,
         ('best', 'suvs'): 3,
         ('suvs', 'done'): 1,
         ('done', 'lot'): 6,
         ('lot', 'winter'): 2,
         ('winter', 'driving'): 21,
         ('driving', 'interior'): 8,
         ('interior', 'alaska'): 1,
         ('alaska', 'heaters'): 1,
         ('heaters', 'kept'): 1,
         ('kept', 'warm'): 1,
         ('warm', 'stopping'): 1,
         ('stopping', 'ability'): 2,
         ('ability', 'icy'): 1,
         ('icy', 'roads'): 6,
         ('roads', 'wonderful'): 1,
         ('wonderful', 'still'): 1,
         ('still', 'made'): 13,
         ('made', 'would'): 2,
         ('would', 'buy'): 133,
         ('buy', 'new'): 72,
         ('new', 'one'): 126,
         ('one', 'make'): 8,
         ('make', 'anymore'): 3,
         ('anymore', 'wheel'): 1,
         ('wheel', 'drive'): 142,
         ('drive', 'version'): 3,
         ('version', 'still'): 1,
         ('still', 'happy'): 27,
         ('happy', 'element'): 5,
         ('element', 'thinking'): 1,
         ('thinking', 'replacing'): 2,
         ('replacing', 'new'): 4,
         ('new', 'rig'): 1,
         ('rig', 'year'): 1,
         ('year', 'would'): 5,
         ('would', 'like'): 91,
         ('like', 'new'): 150,
         ('new', 'safety'): 6,
         ('safety', 'features'): 131,
         ('features', 'vehicle'): 2,
         ('vehicle', 'drive'): 23,
         ('drive', 'daily'): 13,
         ('daily', 'think'): 1,
         ('think', 'honda'): 49,
         ('honda', 'made'): 40,
         ('made', 'real'): 1,
         ('real', 'mistake'): 1,
         ('mistake', 'continuing'): 1,
         ('continuing', 'utilitarian'): 1,
         ('utilitarian', 'vehicle'): 5,
         ('vehicle', 'great'): 28,
         ('little', 'car'): 153,
         ('car', 'newer'): 5,
         ('newer', 'honda'): 7,
         ('honda', 'ground'): 2,
         ('ground', 'clearance'): 23,
         ('clearance', 'would'): 2,
         ('like', 'inches'): 2,
         ('inches', 'snow'): 9,
         ('snow', 'since'): 1,
         ('since', 'december'): 6,
         ('december', 'getting'): 1,
         ('getting', 'around'): 22,
         ('around', 'car'): 39,
         ('car', 'less'): 31,
         ('less', 'clearance'): 1,
         ('would', 'create'): 1,
         ('create', 'problems'): 1,
         ('lowest', 'maintenance'): 1,
         ('maintenance', 'vehicle'): 6,
         ('vehicle', 'ever'): 86,
         ('ever', 'owned'): 304,
         ('owned', 'time'): 1,
         ('time', 'move'): 6,
         ('move', 'need'): 1,
         ('need', 'large'): 2,
         ('large', 'cargo'): 15,
         ('cargo', 'space'): 149,
         ('space', 'anymore'): 1,
         ('anymore', 'transport'): 1,
         ('transport', 'wares'): 1,
         ('wares', 'fun'): 1,
         ('fun', 'drive'): 897,
         ('drive', 'easy'): 24,
         ('easy', 'take'): 5,
         ('take', 'care'): 69,
         ('care', 'love'): 5,
         ('love', 'element'): 29,
         ('thing', 'change'): 2,
         ('change', 'drink'): 1,
         ('drink', 'holders'): 3,
         ('holders', 'hard'): 1,
         ('hard', 'get'): 31,
         ('get', 'arm'): 1,
         ('arm', 'love'): 1,
         ('love', 'cargo'): 6,
         ('cargo', 'room'): 63,
         ('room', 'seats'): 16,
         ('seats', 'folded'): 41,
         ('folded', 'sides'): 1,
         ('sides', 'brought'): 1,
         ('brought', 'gallon'): 1,
         ('gallon', 'water'): 2,
         ('water', 'heater'): 2,
         ('heater', 'home'): 1,
         ('home', 'car'): 7,
         ('car', 'new'): 172,
         ('new', 'dishwasher'): 1,
         ('dishwasher', 'wish'): 1,
         ('wish', 'discontinued'): 1,
         ('discontinued', 'element'): 1,
         ('element', 'would'): 2,
         ('one', 'husband'): 2,
         ('husband', 'simply'): 1,
         ('simply', 'fit'): 2,
         ('fit', 'cars'): 1,
         ('cars', 'got'): 2,
         ('got', 'ease'): 1,
         ('ease', 'getting'): 6,
         ('getting', 'provides'): 1,
         ('provides', 'necessary'): 1,
         ('necessary', 'head'): 1,
         ('head', 'room'): 50,
         ('room', 'hey'): 1,
         ('hey', 'honda'): 4,
         ('honda', 'bring'): 6,
         ('bring', 'back'): 17,
         ('back', 'like'): 8,
         ('like', 'since'): 4,
         ('since', 'first'): 29,
         ('first', 'review'): 9,
         ('review', 'get'): 2,
         ('get', 'rid'): 82,
         ('rid', 'trans'): 1,
         ('trans', 'axels'): 1,
         ('axels', 'major'): 1,
         ('major', 'expenses'): 1,
         ('expenses', 'hit'): 1,
         ('hit', 'car'): 8,
         ('car', 'love'): 120,
         ('love', 'another'): 1,
         ('another', 'buried'): 1,
         ('buried', 'chevrolet'): 1,
         ('chevrolet', 'silverado'): 1,
         ('although', 'bought'): 1,
         ('bought', 'used'): 102,
         ('used', 'months'): 4,
         ('ago', 'odo'): 1,
         ('odo', 'worthwhile'): 1,
         ('worthwhile', 'catagories'): 1,
         ('catagories', 'although'): 1,
         ('although', 'im'): 1,
         ('im', 'used'): 2,
         ('used', 'v'): 2,
         ('v', 'power'): 14,
         ('power', 'vehicles'): 1,
         ('vehicles', 'still'): 3,
         ('still', 'peppy'): 1,
         ('peppy', 'enough'): 6,
         ('enough', 'although'): 2,
         ('although', 'wish'): 3,
         ('wish', 'got'): 5,
         ('got', 'better'): 28,
         ('better', 'gas'): 107,
         ('gas', 'mileage'): 1454,
         ('mileage', 'maybe'): 2,
         ('maybe', 'used'): 2,
         ('used', 'overall'): 7,
         ('overall', 'would'): 16,
         ('would', 'give'): 24,
         ('give', 'definate'): 1,
         ('definate', 'thumbs'): 2,
         ('thumbs', 'dependable'): 1,
         ('dependable', 'durable'): 1,
         ('durable', 'cant'): 1,
         ('cant', 'wait'): 6,
         ('wait', 'try'): 2,
         ('try', 'snow'): 2,
         ('snow', 'year'): 6,
         ('year', 'ne'): 1,
         ('ne', 'iowa'): 1,
         ('iowa', 'course'): 1,
         ('course', 'almost'): 1,
         ('almost', 'sure'): 1,
         ('sure', 'would'): 9,
         ('would', 'love'): 25,
         ('love', 'honda'): 122,
         ('honda', 'known'): 14,
         ('known', 'reliability'): 7,
         ('car', 'three'): 24,
         ('three', 'years'): 84,
         ('years', 'miles'): 80,
         ('miles', 'drove'): 25,
         ('drove', 'across'): 4,
         ('across', 'country'): 27,
         ('country', 'montana'): 1,
         ('montana', 'year'): 1,
         ('year', 'drive'): 2,
         ('drive', 'good'): 31,
         ('good', 'remarkable'): 2,
         ('remarkable', 'gearbox'): 1,
         ('gearbox', 'solid'): 1,
         ('solid', 'smooth'): 4,
         ('smooth', 'turning'): 1,
         ('turning', 'radius'): 53,
         ('radius', 'good'): 6,
         ('good', 'build'): 11,
         ('build', 'quality'): 187,
         ('quality', 'great'): 22,
         ('great', 'problems'): 14,
         ('problems', 'engine'): 11,
         ('engine', 'regular'): 1,
         ('regular', 'maintenance'): 88,
         ('maintenance', 'problems'): 14,
         ('problems', 'realtime'): 1,
         ('realtime', 'wheel'): 1,
         ('drive', 'cargo'): 1,
         ('cargo', 'capacity'): 26,
         ('capacity', 'car'): 2,
         ('car', 'marketed'): 2,
         ('marketed', 'young'): 1,
         ('young', 'adventure'): 1,
         ('adventure', 'vehicle'): 1,
         ('vehicle', 'well'): 14,
         ('well', 'gross'): 1,
         ('gross', 'payload'): 1,
         ('payload', 'ish'): 1,
         ('ish', 'lbs'): 1,
         ('lbs', 'people'): 2,
         ('people', 'generally'): 1,
         ('generally', 'hits'): 1,
         ('hits', 'limit'): 1,
         ('limit', 'gear'): 1,
         ('gear', 'long'): 2,
         ('long', 'keep'): 6,
         ('keep', 'light'): 1,
         ('light', 'ok'): 1,
         ('ok', 'awd'): 1,
         ('awd', 'slow'): 1,
         ('slow', 'react'): 2,
         ('react', 'slipping'): 1,
         ('slipping', 'wheels'): 1,
         ('wheels', 'start'): 2,
         ('start', 'sliding'): 1,
         ('sliding', 'spinning'): 1,
         ('spinning', 'wheels'): 1,
         ('wheels', 'often'): 1,
         ('often', 'point'): 1,
         ('point', 'tilt'): 1,
         ('tilt', 'sunroof'): 1,
         ('bought', 'honda'): 163,
         ('honda', 'element'): 42,
         ('element', 'miles'): 3,
         ('miles', 'drives'): 9,
         ('drives', 'like'): 153,
         ('like', 'brand'): 25,
         ('brand', 'new'): 372,
         ('new', 'car'): 359,
         ('car', 'gon'): 1,
         ('gon', 'na'): 31,
         ('na', 'purchased'): 1,
         ('purchased', 'saturn'): 1,
         ('saturn', 'vue'): 4,
         ('vue', 'promised'): 1,
         ('promised', 'another'): 1,
         ('another', 'buyer'): 1,
         ('buyer', 'stroke'): 1,
         ('stroke', 'luck'): 1,
         ('luck', 'dealer'): 1,
         ('dealer', 'element'): 1,
         ('element', 'available'): 1,
         ('available', 'yes'): 2,
         ('yes', 'bit'): 3,
         ('bit', 'bouncy'): 2,
         ('bouncy', 'impressed'): 1,
         ('impressed', 'everything'): 2,
         ('everything', 'element'): 2,
         ('element', 'even'): 1,
         ('even', 'almost'): 4,
         ('almost', 'years'): 65,
         ('years', 'old'): 174,
         ('old', 'turning'): 1,
         ('turning', 'heads'): 2,
         ('heads', 'got'): 1,
         ('got', 'silver'): 3,
         ('silver', 'c'): 1,
         ('c', 'handsome'): 1,
         ('handsome', 'practical'): 1,
         ('practical', 'car'): 17,
         ('car', 'looking'): 35,
         ('looking', 'cadillac'): 1,
         ('cadillac', 'ride'): 1,
         ('ride', 'wont'): 1,
         ('wont', 'like'): 1,
         ('like', 'looking'): 3,
         ('looking', 'great'): 18,
         ('great', 'fun'): 28,
         ('drive', 'practical'): 5,
         ('practical', 'people'): 1,
         ('people', 'property'): 1,
         ('property', 'hauler'): 1,
         ('hauler', 'look'): 1,
         ('look', 'elements'): 1,
         ('elements', 'far'): 1,
         ('far', 'interior'): 4,
         ('interior', 'either'): 1,
         ('either', 'like'): 5,
         ('like', 'dislike'): 3,
         ('dislike', 'triple'): 1,
         ('triple', 'design'): 1,
         ('design', 'nice'): 10,
         ('nice', 'touch'): 15,
         ('touch', 'get'): 1,
         ('get', 'one'): 56,
         ('element', 'lacks'): 1,
         ('lacks', 'features'): 2,
         ('features', 'auto'): 3,
         ('auto', 'headlights'): 10,
         ('headlights', 'usb'): 1,
         ('usb', 'power'): 1,
         ('power', 'seats'): 17,
         ('seats', 'sunroof'): 8,
         ('sunroof', 'etc'): 2,
         ('etc', 'gas'): 4,
         ('mileage', 'less'): 8,
         ('less', 'would'): 4,
         ('would', 'expect'): 45,
         ('expect', 'honda'): 27,
         ('honda', 'honesty'): 1,
         ('honesty', 'could'): 1,
         ('could', 'care'): 5,
         ('care', 'less'): 9,
         ('less', 'absolutely'): 2,
         ('absolutely', 'love'): 95,
         ('love', 'car'): 503,
         ('car', 'even'): 68,
         ('even', 'give'): 1,
         ('give', 'thing'): 2,
         ('thing', 'lower'): 1,
         ('lower', 'ratings'): 2,
         ('ratings', 'rarely'): 1,
         ('rarely', 'cite'): 1,
         ('cite', 'real'): 1,
         ('real', 'material'): 1,
         ('material', 'issues'): 1,
         ('issues', 'engine'): 4,
         ('engine', 'transmission'): 41,
         ('transmission', 'issues'): 36,
         ('issues', 'stereo'): 1,
         ('stereo', 'great'): 14,
         ('great', 'factory'): 2,
         ('factory', 'set'): 1,
         ('set', 'absolutely'): 1,
         ('absolutely', 'one'): 1,
         ('one', 'favorite'): 8,
         ('favorite', 'purchases'): 1,
         ('fell', 'love'): 53,
         ('love', 'vehicle'): 39,
         ('vehicle', 'showroom'): 1,
         ('showroom', 'still'): 1,
         ('still', 'enjoy'): 13,
         ('enjoy', 'driving'): 60,
         ('driving', 'alot'): 1,
         ('alot', 'features'): 1,
         ('features', 'may'): 1,
         ('may', 'right'): 1,
         ('right', 'everyone'): 2,
         ('everyone', 'homework'): 1,

#### Get the most frequest bigrams or trigrams

In [57]:
# Get the most frequent bi-grams or trigrams in positive reviews
most_common_positive_bi_grams = positive_bi_gram_counts.most_common(30)  # Change 10 to your desired number
# Get the most frequent bi-grams or trigrams in negative reviews
most_common_negative_bi_grams = negative_bi_gram_counts.most_common(30)  # Change 10 to your desired number

print("Most Common Bi-grams/Trigrams in Positive Reviews:")
for bi_gram, count in most_common_positive_bi_grams:
    print(f"{' '.join(bi_gram)}: {count}")

print("\nMost Common Bi-grams/Trigrams in Negative Reviews:")
for bi_gram, count in most_common_negative_bi_grams:
    print(f"{' '.join(bi_gram)}: {count}")

Most Common Bi-grams/Trigrams in Positive Reviews:
gas mileage: 1454
k miles: 1186
fun drive: 897
great car: 735
bought car: 657
cr v: 576
fuel economy: 515
love car: 503
road noise: 499
honda civic: 407
car x: 391
honda accord: 378
ex l: 378
brand new: 372
new car: 359
great gas: 339
get mpg: 330
ever owned: 304
car great: 294
car ever: 283
x car: 280
oil changes: 272
around town: 271
best car: 262
much better: 258
steering wheel: 247
sound system: 239
back seat: 236
buy another: 234
average mpg: 233

Most Common Bi-grams/Trigrams in Negative Reviews:
buy another honda: 29
check engine light: 23
never buy another: 22
never buy honda: 18
car ever owned: 16
miles per gallon: 16
honda cr v: 14
buy another one: 13
power steering pump: 13
bought car new: 12
good gas mileage: 11
honda customer service: 11
would buy another: 10
class action lawsuit: 10
worst car ever: 10
brand new car: 10
tu tu tu: 10
honda stand behind: 9
first last honda: 9
car k miles: 9
better gas mileage: 9
bought car used: 9
car brand new: 9
honda civic ex: 9
gas mileage mpg: 8
honda knows problem: 8
odyssey ex l: 8
k miles k: 8
driver side window: 8
class action suit: 8

In [66]:
df_most_common_positive = pd.DataFrame(most_common_positive_bi_grams, columns=['Bi-gram/Trigram', 'Count'])
df_most_common_negative = pd.DataFrame(most_common_negative_bi_grams, columns=['Bi-gram/Trigram', 'Count'])

In [67]:
df_most_common_positive

      Bi-gram/Trigram  Count
0      (gas, mileage)   1454
1          (k, miles)   1186
2        (fun, drive)    897
3        (great, car)    735
4       (bought, car)    657
5             (cr, v)    576
6     (fuel, economy)    515
7         (love, car)    503
8       (road, noise)    499
9      (honda, civic)    407
10           (car, x)    391
11    (honda, accord)    378
12            (ex, l)    378
13       (brand, new)    372
14         (new, car)    359
15       (great, gas)    339
16         (get, mpg)    330
17      (ever, owned)    304
18       (car, great)    294
19        (car, ever)    283
20           (x, car)    280
21     (oil, changes)    272
22     (around, town)    271
23        (best, car)    262
24     (much, better)    258
25  (steering, wheel)    247
26    (sound, system)    239
27       (back, seat)    236
28     (buy, another)    234
29     (average, mpg)    233

In [68]:
df_most_common_negative

               Bi-gram/Trigram  Count
0        (buy, another, honda)     29
1       (check, engine, light)     23
2        (never, buy, another)     22
3          (never, buy, honda)     18
4           (car, ever, owned)     16
5         (miles, per, gallon)     16
6               (honda, cr, v)     14
7          (buy, another, one)     13
8      (power, steering, pump)     13
9           (bought, car, new)     12
10        (good, gas, mileage)     11
11  (honda, customer, service)     11
12       (would, buy, another)     10
13    (class, action, lawsuit)     10
14          (worst, car, ever)     10
15           (brand, new, car)     10
16                (tu, tu, tu)     10
17      (honda, stand, behind)      9
18        (first, last, honda)      9
19             (car, k, miles)      9
20      (better, gas, mileage)      9
21         (bought, car, used)      9
22           (car, brand, new)      9
23          (honda, civic, ex)      9
24         (gas, mileage, mpg)      8
25     (honda, knows, problem)      8
26            (odyssey, ex, l)      8
27               (k, miles, k)      8
28      (driver, side, window)      8
29       (class, action, suit)      8

In [69]:
df_most_common_positive.to_excel('common_positive.xlsx',index=False)
df_most_common_negative.to_excel('common_negative.xlsx',index=False)

In [60]:
df3.head()

                   Review_Date      Author_Name                                      Vehicle_Title                        Review_Title                                             Review  Rating  Sentiment Sentiment_Category                                   Tokenized_Review
0   on 03/01/17 13:11 PM (PST)      kris corah   2007 Honda Element SUV LX 4dr SUV AWD (2.4L 4c...                QUIRKY AND PRACTICAL  years element honestly much complain never gre...     4.0   0.142614           Positive  [years, element, honestly, much, complain, nev...
1   on 09/02/16 18:22 PM (PDT)  Carol Shafford   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...       Go Anywhere with your Element  owned element since purchased new great little...     5.0   0.318987           Positive  [owned, element, since, purchased, new, great,...
2   on 11/12/15 08:04 AM (PST)            Gale   2007 Honda Element SUV EX 4dr SUV AWD (2.4L 4c...                    Such a cool car!  lowest maintenance vehicle ever owned time mov...     1.0   0.361905           Positive  [lowest, maintenance, vehicle, ever, owned, ti...
3   on 08/13/15 15:40 PM (PDT)    Judy Eastham    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5M)  From soup to nuts, it does it all.  thing change drink holders hard get arm love c...     5.0   0.169356           Positive  [thing, change, drink, holders, hard, get, arm...
4   on 03/14/13 10:38 AM (PDT)  boeserkritiker    2007 Honda Element SUV LX 4dr SUV (2.4L 4cyl 5A)                          good value  bought vehicle new got k miles served us relia...     4.0  -0.019043           Negative  [bought, vehicle, new, got, k, miles, served, ...

In [61]:
df3.to_excel('Sentiment_analysis.xlsx',index=False)